### ISSUE TITLE
Consider license change for ammonia_bench

### ISSUE THREAD

**Issue by haxney** [notriddle/rust-ammonia#1]
The [WTFPL](http://www.wtfpl.net/txt/copying/) is fun, but its suitability as an actual legal license is questionable. If you want companies to be able to use the code, consider using a "normal" license with similar permissions such as Apache, MIT, or BSD.

IANAL, etc.

**Comment by notriddle** [comment]
You may not be a lawyer, but the [FSF](http://www.gnu.org/licenses/license-list.en.html#WTFPL) and the [Debian Project](https://lists.debian.org/debian-legal/2002/09/msg00036.html) do have lawyers. It is a valid free and open source software license, and it means exactly what it sounds like it means. If you object to the language, you don't need to include the copyright notice when you redistribute the benchmark.

In case you're wondering why the benchmark and the main library are under different licenses, I use the WTFPL for anything where enforcing the license would be more trouble than it's worth. "You want to use a tweaked version of that benchmark harness, and you don't want to attribute me? Whatever. It's only ten lines of code." All of the licenses you listed, by the way, require attribution.

If you want to contribute to the benchmark and don't want to give away your changes, then I'll happily incorporate your changes under another license. Similarly, if the benchmark ends up becoming nontrivial, I'll relicense it under the Apache license.
